[toolchain]

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
anchor_movie_review_program = "8vMikvL1QYW4oWjb9YLD4Pb1WCC6fYJt55YuEtanm4Hd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
